name: diamon_rose_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.63

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  animations: ^2.0.1
  audio_video_progress_bar: ^0.9.0
  badges: ^2.0.1
  cached_network_image: ^3.1.0
  camera: ^0.9.4+5
  connectivity: ^3.0.6
  crawl_splash: ^0.1.0
  cupertino_icons: ^1.0.3
  date_time_picker: ^2.1.0
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  extended_image: ^4.0.1
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.3
  flutter_easyloading: ^3.0.3
  flutter_local_notifications: ^8.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^1.2.3
  flutter_stripe: ^1.3.0
  flutter_svg: ^0.22.0
  freezed_annotation: ^0.14.1
  get: ^4.3.8
  global_configuration: ^2.0.0-nullsafety.0
  image_editor: ^1.0.2
  image_picker: ^0.8.4+2
  intl: ^0.17.0-nullsafesty
  intl_generator: ^0.1.0+0
  package_info_plus: ^1.0.6
  path_provider: ^2.0.5
  permission_handler: ^8.1.6
  pin_code_fields: ^7.3.0
  preload_page_view: ^0.1.6
  rxdart: ^0.27.2
  share_plus: ^2.1.4
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0
  simple_tooltip: ^1.0.0
  sliding_up_panel: ^2.0.0+1
  universal_platform: ^1.0.0+1
  uuid: ^3.0.4
  video_player: ^2.2.6
  video_thumbnail: ^0.4.3
  widget_circular_animator: ^1.0.0

dev_dependencies:
  build_runner:
  flutter_lints: any
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+2
  json_serializable: ^4.1.0
  pedantic: ^1.11.1

flutter_native_splash:
  background_image: "assets/images/png/app_background.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/gif/
    - assets/images/png/
    - assets/images/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: TikTokIcons
      fonts:
        - asset: assets/fonts/TikTokIcons.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
